# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0534ef3c8f8015191849a2f82720abe03d2c4198491d9fc18fca47406e7cc11e1204eb12e2bcb829d0239ee68d1728d69d4dfc09e6f76cde974a58053fafcdde

test:
  secret_key_base: d654bb77022d08d74cb31eba6d879e60ba161a0754a2050b62d70ef876ca4985d7d979c5fc7bf6ece09e16ca61f49b995478b19d5486d988374152a04bcf5942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
